### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by msimerson** [cloud-css/Infopoint#1]
- Cloud **C**ontent **S**canning **S**erver
  - Pros
    - In Use - no need to rename
  - Cons
    - name collision with CSS
- Cloud **E**mail **S**canning **S**erver
  - Pros
    - More precise name, "oh, it scan's emails." Do we scan anything else?
  - Cons
    - Requires some renaming work
- **E**mail **C**ontent **S**canner
  - Pros
    - doesn't use the word 'Server', better for a SaaS
- ...

**Comment by Dexus** [comment]
I'm then for ECS.

**Comment by msimerson** [comment]
> I'm then for ECS.

Right now, that's the way I feel as well. Lets think about it for a few days and see if we both feel the same way.
